name: seqproft
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.9.1
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - cpython=3.11.11
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.77
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - dav1d=1.2.1
  - ffmpeg=7.1.0
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.14
  - h2=4.1.0
  - harfbuzz=10.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - intel-openmp=2022.0.1
  - jinja2=3.1.5
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libass=0.17.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.23
  - libdrm=2.4.124
  - libegl=1.7.0
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenvino=2024.5.0
  - libopenvino-auto-batch-plugin=2024.5.0
  - libopenvino-auto-plugin=2024.5.0
  - libopenvino-hetero-plugin=2024.5.0
  - libopenvino-intel-cpu-plugin=2024.5.0
  - libopenvino-intel-gpu-plugin=2024.5.0
  - libopenvino-intel-npu-plugin=2024.5.0
  - libopenvino-ir-frontend=2024.5.0
  - libopenvino-onnx-frontend=2024.5.0
  - libopenvino-paddle-frontend=2024.5.0
  - libopenvino-pytorch-frontend=2024.5.0
  - libopenvino-tensorflow-frontend=2024.5.0
  - libopenvino-tensorflow-lite-frontend=2024.5.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.44
  - libprotobuf=5.28.2
  - librsvg=2.58.4
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.2
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - openh264=2.5.0
  - openjpeg=2.5.3
  - openssl=3.4.0
  - pango=1.54.0
  - pcre2=10.44
  - pillow=11.0.0
  - pip=24.3.1
  - pixman=0.44.2
  - pthread-stubs=0.4
  - pugixml=1.14
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.11.11
  - python_abi=3.11
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.6.0
  - snappy=1.2.1
  - svt-av1=2.3.0
  - sympy=1.13.3
  - tbb=2022.0.0
  - tk=8.6.13
  - torchaudio=2.2.1
  - torchtriton=2.2.0
  - torchvision=0.17.1
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wayland=1.23.1
  - wayland-protocols=1.37
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - yaml=0.2.5
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==0.29.3
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - appdirs==1.4.4
      - attrs==24.3.0
      - click==8.1.8
      - datasets==2.19.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - frozenlist==1.5.0
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.27.0
      - joblib==1.4.2
      - multidict==6.1.0
      - multiprocess==0.70.16
      - numpy==1.26.4
      - packaging==24.2
      - pandas==2.2.3
      - peft==0.10.0
      - propcache==0.2.1
      - protobuf==4.25.5
      - psutil==6.1.1
      - pyarrow==18.1.0
      - pyarrow-hotfix==0.6
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - regex==2024.4.16
      - safetensors==0.4.3
      - scikit-learn==1.4.1.post1
      - scipy==1.14.1
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - six==1.17.0
      - smmap==5.0.1
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - tqdm==4.67.1
      - tzdata==2024.2
      - wandb==0.16.6
      - xxhash==3.5.0
      - yarl==1.18.3
