task: determined
goal: multiclass-classification

dataset: 
  dataname: Loc
  csv_root: data/Loc/splits/deeploc_{}.csv
  num_classes: 10

project_name: EsmMHAGraphHead-Loc-35M-nofinetune

esm_config:
  model_name: facebook/esm2_t12_35M_UR50D
  model_size: 35M
  in_features: 480
  hidden_features: 480
  output_attentions: True
  contact_compression: mean_head

head_config:
  head_name: EsmMHAGraphHead
  attention_features: 128
  attention_heads: 4
  dropout_rate: 0.1

fp16: True
quantized: False
peft: False

sweep_config:
  method: random
  parameters: 
    lr:
      value: 0.0005
    lr_scheduler_type:
      value: cosine
    num_train_epochs:
      value: 10
  metric:
    goal: "maximize"
    name: "eval/accuracy"

training_setting:
  per_device_train_batch_size: 16
  per_device_eval_batch_size : 8
  gradient_accumulation_steps: 1
  gradient_checkpointing: False
  criterion: ce
  
metric_for_best_model: accuracy
